### ISSUE TITLE
won't enable openGL 4.1 support

### ISSUE THREAD

**Issue by dpMerchant** [Igalia/mesa#4]
Hello,
I am using an Radeon HD 6530D which on the AMD site shows it supports up to OpenGL 4.1, but your mesa driver will only allow me to use OpenGL 3.0 on Xubuntu 16.04. Why is that? can I change something to enable 4.1? please help.

**Comment by tanty** [comment]
Per driver OpenGL version support in mesa depends on the mesa version used.

You will have to check which version is the one shipped in Xubuntu 16.04 and address this very same question to them.

I'll advice to check at:
https://xubuntu.org/help/

Additionally, for mesa specific bugs and problems, you should address its bugzilla, at:
https://bugs.freedesktop.org/describecomponents.cgi?product=Mesa

In any case, this is not the proper issue tracker for this kind of question. Hence, closing.
